import { StyleSheet } from "react-native";

const stylesColors = StyleSheet.create({
    container: {
        flexGrow: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: "#B9E9E8"
    },
    contentcard: {
        width: 380,
        height: 250,
        borderRadius: 20,
        backgroundColor: "#41C9E2",
        margin: 20,
        alignItems: "center",
    },
    textcard: {
        width: '95%',
        height: '50%',
        borderRadius: 20,
        backgroundColor: "#fff",
        justifyContent: "center",
        alignItems: "center",
        margin: 20,
    },
    title: {
        fontSize: 16,
        fontWeight: 'bold',
    },
    imgcardWh: {
        width: 80,
        height: 80,
        marginTop: 10,
        backgroundColor: "#fff",
        borderRadius: 50,
        justifyContent: "center",
        alignItems: "center",
    },
    imgcardYL: {
        width: 80,
        height: 80,
        marginTop: 10,
        backgroundColor: "#F2F200",
        borderRadius: 50,
        justifyContent: "center",
        alignItems: "center",
    },
    imgcardGr: {
        width: 80,
        height: 80,
        marginTop: 10,
        backgroundColor: "#CACACA",
        borderRadius: 50,
        justifyContent: "center",
        alignItems: "center",
    },
    imgcardRe: {
        width: 80,
        height: 80,
        marginTop: 10,
        backgroundColor: "#EE2720",
        borderRadius: 50,
        justifyContent: "center",
        alignItems: "center",
    },
    imgcardPP: {
        width: 80,
        height: 80,
        marginTop: 10,
        backgroundColor: "#9700C7",
        borderRadius: 50,
        justifyContent: "center",
        alignItems: "center",
    },
    imgcardBlu: {
        width: 80,
        height: 80,
        marginTop: 10,
        backgroundColor: "#033EDA",
        borderRadius: 50,
        justifyContent: "center",
        alignItems: "center",
    },
    imgcardDG: {
        width: 80,
        height: 80,
        marginTop: 10,
        backgroundColor: "#015301",
        borderRadius: 50,
        justifyContent: "center",
        alignItems: "center",
    },
    imgcardBl: {
        width: 80,
        height: 80,
        marginTop: 10,
        backgroundColor: "#000000",
        borderRadius: 50,
        justifyContent: "center",
        alignItems: "center",
    },

});
export default stylesColors;